{% set name = "opentelemetry-exporter-otlp-proto-http" %}
{% set version = "1.15.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/opentelemetry_exporter_otlp_proto_http-{{ version }}.tar.gz
  sha256: 11b2c814249a49b22f6cca7a06b05701f561d577b747f3660dfd67b6eb9daf9c

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
    - hatchling
  run:
    - backoff <3.0.0,>=1.10.0
    - python >=3.7
    - googleapis-common-protos >=1.52,<2.dev0
    - opentelemetry-api >=1.12,<2.dev0
    - opentelemetry-proto ==1.15.0
    - opentelemetry-sdk >=1.12,<2.dev0
    - requests >=2.7,<3.dev0

test:
  imports:
    - opentelemetry
    - opentelemetry.exporter
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/open-telemetry/opentelemetry-python/tree/main/exporter/opentelemetry-exporter-otlp-proto-http
  summary: OpenTelemetry Collector Protobuf over HTTP Exporter
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mariusvniekerk
