{% set name = "opentelemetry-exporter-otlp-proto-http" %}
{% set version = "1.19.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/opentelemetry_exporter_otlp_proto_http-{{ version }}.tar.gz
  sha256: 7c8d2c1268cef4d9c1b13a1399f510e3c3dbb88c52f54597d487a128a23b681e

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
    - hatchling
  run:
    - python >=3.8
    - googleapis-common-protos >=1.52,<2.0
    - opentelemetry-api >=1.15,<2.0
    - opentelemetry-proto =={{ version }}
    - opentelemetry-sdk =={{ version }}
    - opentelemetry-exporter-otlp-proto-common =={{ version }}
    - requests >=2.7,<3.dev0
  # NOTE backoff only required for py<37 but pip checks fails without it
    - backoff >=1.10.0,<2.0.0

test:
  imports:
    - opentelemetry
    - opentelemetry.exporter
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/open-telemetry/opentelemetry-python/tree/main/exporter/opentelemetry-exporter-otlp-proto-http
  summary: OpenTelemetry Collector Protobuf over HTTP Exporter
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
    - mariusvniekerk
