{% set name = "opentelemetry-exporter-otlp-proto-http" %}
{% set version = "1.21.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/opentelemetry_exporter_otlp_proto_http-{{ version }}.tar.gz
  sha256: 19d60afa4ae8597f7ef61ad75c8b6c6b7ef8cb73a33fb4aed4dbc86d5c8d3301

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python >=3.8
    - hatchling
    - pip
  run:
    - python >=3.8
    - deprecated >=1.2.6
    - googleapis-common-protos >=1.52,<2.0
    - opentelemetry-api >=1.15,<2.0
    - opentelemetry-proto =={{ version }}
    - opentelemetry-sdk =={{ version }}
    - opentelemetry-exporter-otlp-proto-common =={{ version }}
    - requests >=2.7,<3.0
  # NOTE backoff only required for py<37 but pip checks fails without it
    - backoff >=1.10.0,<2.0.0

test:
  imports:
    - opentelemetry
    - opentelemetry.exporter
    - opentelemetry.exporter.otlp.proto.http
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/open-telemetry/opentelemetry-python/tree/main/exporter/opentelemetry-exporter-otlp-proto-http
  summary: OpenTelemetry Collector Protobuf over HTTP Exporter
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
    - mariusvniekerk
